"""usage and usage_drops

Revision ID: 870e713a9fd0
Revises: 
Create Date: 2026-09-28 14:11:46.554596+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '870e713a9fd0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('model_key', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('caller', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage'))
    )
    op.create_index('ix_usage_alias_occurred', 'usage', ['alias', 'occurred_at'], unique=False)
    op.create_index('ix_usage_model_occurred', 'usage', ['model_key', 'occurred_at'], unique=False)
    op.create_index('ix_usage_session_occurred', 'usage', ['session_id', 'occurred_at'], unique=False)
    op.create_table('usage_drops',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('dropped_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_drops'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_drops')
    op.drop_index('ix_usage_session_occurred', table_name='usage')
    op.drop_index('ix_usage_model_occurred', table_name='usage')
    op.drop_index('ix_usage_alias_occurred', table_name='usage')
    op.drop_table('usage')
    # ### end Alembic commands ###
