"""tool execution

Revision ID: b116e423a0da
Revises: 5a3ce69ec387
Create Date: 2026-09-28 18:07:44.401642+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b116e423a0da'
down_revision: str | None = '5a3ce69ec387'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_execution',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('idem_key', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('side_effect', sa.String(length=16), nullable=False),
    sa.Column('args_digest', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('caller', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('result_truncated', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_bytes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_execution')),
    sa.UniqueConstraint('scope', 'idem_key', name='uq_tool_execution_scope_idem')
    )
    op.create_index('ix_tool_execution_session_started', 'tool_execution', ['session_id', 'started_at'], unique=False)
    op.create_index('ix_tool_execution_state_started', 'tool_execution', ['state', 'started_at'], unique=False)
    op.create_index('ix_tool_execution_trace', 'tool_execution', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_execution_trace', table_name='tool_execution')
    op.drop_index('ix_tool_execution_state_started', table_name='tool_execution')
    op.drop_index('ix_tool_execution_session_started', table_name='tool_execution')
    op.drop_table('tool_execution')
    # ### end Alembic commands ###
