"""event table

Revision ID: b520bdbd3c11
Revises: 870e713a9fd0
Create Date: 2026-09-28 15:15:26.974428+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b520bdbd3c11'
down_revision: str | None = '870e713a9fd0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('caller', sa.Text(), nullable=True),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('model_key', sa.Text(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    sa.UniqueConstraint('event_id', name=op.f('uq_event_event_id'))
    )
    op.create_index('ix_event_name_occurred', 'event', ['name', 'occurred_at'], unique=False)
    op.create_index('ix_event_occurred', 'event', ['occurred_at'], unique=False)
    op.create_index('ix_event_session', 'event', ['session_id', 'occurred_at'], unique=False)
    op.create_index('ix_event_trace', 'event', ['trace_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_trace', table_name='event')
    op.drop_index('ix_event_session', table_name='event')
    op.drop_index('ix_event_occurred', table_name='event')
    op.drop_index('ix_event_name_occurred', table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
